"use client"

import { useState } from "react"
import { Search, Users, TrendingUp, Star, MapPin, Filter, Grid, List } from "lucide-react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import PlayerComparison from "./components/player-comparison"
import { PlayerDetail } from "./components/player-detail"

export default function Home() {
  const [search, setSearch] = useState("")
  const [selectedPlayerId, setSelectedPlayerId] = useState<number | null>(null)
  const [comparisonPlayers, setComparisonPlayers] = useState<number[]>([])
  const [showComparison, setShowComparison] = useState(false)
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid")

  // Updated players array with better images and data
  const players = [
    {
      id: 1,
      name: "Lionel Messi",
      team: "Inter Miami",
      position: "RW",
      age: 36,
      nationality: "Argentina",
      height: "1.70m",
      weight: "72kg",
      preferredFoot: "Sol",
      marketValue: "25M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/28003-1671435885.jpg",
      stats: {
        goals: 21,
        assists: 20,
        matches: 37,
        minutes: 2890,
        starts: 35,
        yellowCards: 4,
        redCards: 0,
        rating: 8.9,
        shots: 89,
        shotsOnTarget: 45,
        shotsOffTarget: 32,
        shotsBlocked: 12,
        shotAccuracy: 51,
        passes: 2156,
        passesCompleted: 1897,
        passAccuracy: 88,
        keyPasses: 67,
        throughBalls: 23,
        longBalls: 45,
        crosses: 34,
        crossAccuracy: 32,
        dribbles: 89,
        dribblesSuccessful: 67,
        dribblesAttempted: 98,
        dribblingSuccessRate: 68,
        touches: 2890,
        touchesInBox: 156,
        tackles: 23,
        tacklesWon: 18,
        interceptions: 12,
        clearances: 8,
        blocks: 5,
        duelsWon: 145,
        duelsLost: 89,
        aerialDuelsWon: 12,
        aerialDuelsLost: 23,
        distanceCovered: 356.7,
        sprints: 234,
        topSpeed: 32.5,
        foulsCommitted: 18,
        foulsDrawn: 45,
        offsides: 12,
        penalties: 3,
        penaltiesScored: 3,
        penaltiesMissed: 0,
        bigChancesCreated: 34,
        bigChancesMissed: 8,
      },
    },
    {
      id: 2,
      name: "Cristiano Ronaldo",
      team: "Al Nassr",
      position: "ST",
      age: 39,
      nationality: "Portugal",
      height: "1.87m",
      weight: "84kg",
      preferredFoot: "Sağ",
      marketValue: "15M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/8198-1694609670.jpg",
      stats: {
        goals: 35,
        assists: 11,
        matches: 31,
        minutes: 2654,
        starts: 30,
        yellowCards: 2,
        redCards: 0,
        rating: 8.7,
        shots: 156,
        shotsOnTarget: 67,
        shotsOffTarget: 67,
        shotsBlocked: 22,
        shotAccuracy: 43,
        passes: 1234,
        passesCompleted: 1012,
        passAccuracy: 82,
        keyPasses: 45,
        throughBalls: 12,
        longBalls: 23,
        crosses: 12,
        crossAccuracy: 25,
        dribbles: 34,
        dribblesSuccessful: 23,
        dribblesAttempted: 45,
        dribblingSuccessRate: 51,
        touches: 1890,
        touchesInBox: 234,
        tackles: 12,
        tacklesWon: 8,
        interceptions: 6,
        clearances: 15,
        blocks: 3,
        duelsWon: 123,
        duelsLost: 67,
        aerialDuelsWon: 89,
        aerialDuelsLost: 34,
        distanceCovered: 298.4,
        sprints: 189,
        topSpeed: 33.8,
        foulsCommitted: 23,
        foulsDrawn: 34,
        offsides: 23,
        penalties: 8,
        penaltiesScored: 7,
        penaltiesMissed: 1,
        bigChancesCreated: 23,
        bigChancesMissed: 12,
      },
    },
    {
      id: 3,
      name: "Kylian Mbappé",
      team: "Real Madrid",
      position: "LW",
      age: 25,
      nationality: "France",
      height: "1.78m",
      weight: "73kg",
      preferredFoot: "Sağ",
      marketValue: "180M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/342229-1682683695.jpg?lm=1",
      stats: {
        goals: 26,
        assists: 8,
        matches: 29,
        minutes: 2456,
        starts: 28,
        yellowCards: 3,
        redCards: 0,
        rating: 8.5,
        shots: 98,
        shotsOnTarget: 52,
        shotsOffTarget: 34,
        shotsBlocked: 12,
        shotAccuracy: 53,
        passes: 1567,
        passesCompleted: 1332,
        passAccuracy: 85,
        keyPasses: 56,
        throughBalls: 18,
        longBalls: 34,
        crosses: 23,
        crossAccuracy: 35,
        dribbles: 67,
        dribblesSuccessful: 45,
        dribblesAttempted: 78,
        dribblingSuccessRate: 58,
        touches: 2234,
        touchesInBox: 189,
        tackles: 18,
        tacklesWon: 12,
        interceptions: 15,
        clearances: 5,
        blocks: 2,
        duelsWon: 134,
        duelsLost: 78,
        aerialDuelsWon: 23,
        aerialDuelsLost: 45,
        distanceCovered: 312.8,
        sprints: 345,
        topSpeed: 37.9,
        foulsCommitted: 15,
        foulsDrawn: 67,
        offsides: 18,
        penalties: 2,
        penaltiesScored: 2,
        penaltiesMissed: 0,
        bigChancesCreated: 28,
        bigChancesMissed: 15,
      },
    },
    {
      id: 4,
      name: "Erling Haaland",
      team: "Manchester City",
      position: "ST",
      age: 23,
      nationality: "Norway",
      height: "1.94m",
      weight: "94kg",
      preferredFoot: "Sol",
      marketValue: "180M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/580653-1666598424.jpg?lm=1",
      stats: {
        goals: 38,
        assists: 9,
        matches: 35,
        minutes: 2987,
        starts: 34,
        yellowCards: 1,
        redCards: 0,
        rating: 8.8,
        shots: 145,
        shotsOnTarget: 78,
        shotsOffTarget: 56,
        shotsBlocked: 11,
        shotAccuracy: 54,
        passes: 987,
        passesCompleted: 876,
        passAccuracy: 89,
        keyPasses: 34,
        throughBalls: 8,
        longBalls: 12,
        crosses: 5,
        crossAccuracy: 20,
        dribbles: 23,
        dribblesSuccessful: 15,
        dribblesAttempted: 30,
        dribblingSuccessRate: 50,
        touches: 1567,
        touchesInBox: 256,
        tackles: 9,
        tacklesWon: 7,
        interceptions: 4,
        clearances: 10,
        blocks: 1,
        duelsWon: 156,
        duelsLost: 78,
        aerialDuelsWon: 90,
        aerialDuelsLost: 45,
        distanceCovered: 321.5,
        sprints: 290,
        topSpeed: 36.7,
        foulsCommitted: 10,
        foulsDrawn: 23,
        offsides: 20,
        penalties: 5,
        penaltiesScored: 5,
        penaltiesMissed: 0,
        bigChancesCreated: 18,
        bigChancesMissed: 10,
      },
    },
    {
      id: 5,
      name: "Kevin De Bruyne",
      team: "Manchester City",
      position: "CM",
      age: 32,
      nationality: "Belgium",
      height: "1.81m",
      weight: "76kg",
      preferredFoot: "Sağ",
      marketValue: "70M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/50202-1666254436.jpg?lm=1",
      stats: {
        goals: 10,
        assists: 25,
        matches: 32,
        minutes: 2765,
        starts: 31,
        yellowCards: 2,
        redCards: 0,
        rating: 8.6,
        shots: 67,
        shotsOnTarget: 34,
        shotsOffTarget: 23,
        shotsBlocked: 10,
        shotAccuracy: 51,
        passes: 2345,
        passesCompleted: 2100,
        passAccuracy: 90,
        keyPasses: 89,
        throughBalls: 34,
        longBalls: 56,
        crosses: 45,
        crossAccuracy: 40,
        dribbles: 56,
        dribblesSuccessful: 34,
        dribblesAttempted: 67,
        dribblingSuccessRate: 51,
        touches: 3000,
        touchesInBox: 123,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 10,
        clearances: 7,
        blocks: 3,
        duelsWon: 112,
        duelsLost: 56,
        aerialDuelsWon: 15,
        aerialDuelsLost: 20,
        distanceCovered: 345.9,
        sprints: 278,
        topSpeed: 31.2,
        foulsCommitted: 12,
        foulsDrawn: 30,
        offsides: 5,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 45,
        bigChancesMissed: 5,
      },
    },
    {
      id: 6,
      name: "Mohamed Salah",
      team: "Liverpool",
      position: "RW",
      age: 31,
      nationality: "Egypt",
      height: "1.75m",
      weight: "71kg",
      preferredFoot: "Sol",
      marketValue: "80M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/148455-1673349150.jpg?lm=1",
      stats: {
        goals: 19,
        assists: 10,
        matches: 30,
        minutes: 2500,
        starts: 29,
        yellowCards: 1,
        redCards: 0,
        rating: 8.4,
        shots: 100,
        shotsOnTarget: 55,
        shotsOffTarget: 35,
        shotsBlocked: 10,
        shotAccuracy: 55,
        passes: 1500,
        passesCompleted: 1350,
        passAccuracy: 90,
        keyPasses: 50,
        throughBalls: 15,
        longBalls: 20,
        crosses: 25,
        crossAccuracy: 30,
        dribbles: 60,
        dribblesSuccessful: 40,
        dribblesAttempted: 70,
        dribblingSuccessRate: 57,
        touches: 2000,
        touchesInBox: 150,
        tackles: 10,
        tacklesWon: 7,
        interceptions: 8,
        clearances: 5,
        blocks: 2,
        duelsWon: 100,
        duelsLost: 60,
        aerialDuelsWon: 10,
        aerialDuelsLost: 15,
        distanceCovered: 300.0,
        sprints: 250,
        topSpeed: 33.0,
        foulsCommitted: 8,
        foulsDrawn: 30,
        offsides: 10,
        penalties: 5,
        penaltiesScored: 4,
        penaltiesMissed: 1,
        bigChancesCreated: 25,
        bigChancesMissed: 10,
      },
    },
    {
      id: 7,
      name: "Neymar Jr",
      team: "Al Hilal",
      position: "LW",
      age: 31,
      nationality: "Brazil",
      height: "1.75m",
      weight: "68kg",
      preferredFoot: "Sağ",
      marketValue: "60M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/68290-1671435783.jpg?lm=1",
      stats: {
        goals: 15,
        assists: 12,
        matches: 28,
        minutes: 2300,
        starts: 27,
        yellowCards: 3,
        redCards: 0,
        rating: 8.3,
        shots: 90,
        shotsOnTarget: 50,
        shotsOffTarget: 30,
        shotsBlocked: 10,
        shotAccuracy: 56,
        passes: 1400,
        passesCompleted: 1250,
        passAccuracy: 89,
        keyPasses: 45,
        throughBalls: 12,
        longBalls: 18,
        crosses: 22,
        crossAccuracy: 28,
        dribbles: 55,
        dribblesSuccessful: 38,
        dribblesAttempted: 65,
        dribblingSuccessRate: 58,
        touches: 1900,
        touchesInBox: 140,
        tackles: 9,
        tacklesWon: 6,
        interceptions: 7,
        clearances: 4,
        blocks: 1,
        duelsWon: 95,
        duelsLost: 55,
        aerialDuelsWon: 9,
        aerialDuelsLost: 13,
        distanceCovered: 290.0,
        sprints: 240,
        topSpeed: 32.0,
        foulsCommitted: 7,
        foulsDrawn: 28,
        offsides: 9,
        penalties: 4,
        penaltiesScored: 3,
        penaltiesMissed: 1,
        bigChancesCreated: 22,
        bigChancesMissed: 9,
      },
    },
    {
      id: 8,
      name: "Virgil van Dijk",
      team: "Liverpool",
      position: "CB",
      age: 32,
      nationality: "Netherlands",
      height: "1.93m",
      weight: "92kg",
      preferredFoot: "Sağ",
      marketValue: "50M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/214105-1666254279.jpg?lm=1",
      stats: {
        goals: 5,
        assists: 2,
        matches: 33,
        minutes: 2900,
        starts: 33,
        yellowCards: 0,
        redCards: 0,
        rating: 8.2,
        shots: 20,
        shotsOnTarget: 10,
        shotsOffTarget: 8,
        shotsBlocked: 2,
        shotAccuracy: 50,
        passes: 2500,
        passesCompleted: 2300,
        passAccuracy: 92,
        keyPasses: 10,
        throughBalls: 2,
        longBalls: 50,
        crosses: 1,
        crossAccuracy: 100,
        dribbles: 5,
        dribblesSuccessful: 3,
        dribblesAttempted: 6,
        dribblingSuccessRate: 50,
        touches: 3200,
        touchesInBox: 50,
        tackles: 25,
        tacklesWon: 20,
        interceptions: 30,
        clearances: 150,
        blocks: 15,
        duelsWon: 200,
        duelsLost: 70,
        aerialDuelsWon: 120,
        aerialDuelsLost: 30,
        distanceCovered: 330.0,
        sprints: 150,
        topSpeed: 30.0,
        foulsCommitted: 5,
        foulsDrawn: 10,
        offsides: 0,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 2,
        bigChancesMissed: 0,
      },
    },
    {
      id: 9,
      name: "Harry Kane",
      team: "Bayern Munich",
      position: "ST",
      age: 30,
      nationality: "England",
      height: "1.88m",
      weight: "89kg",
      preferredFoot: "Sağ",
      marketValue: "90M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/132098-1636032748.jpg?lm=1",
      stats: {
        goals: 30,
        assists: 10,
        matches: 30,
        minutes: 2700,
        starts: 30,
        yellowCards: 2,
        redCards: 0,
        rating: 8.5,
        shots: 120,
        shotsOnTarget: 70,
        shotsOffTarget: 40,
        shotsBlocked: 10,
        shotAccuracy: 58,
        passes: 1300,
        passesCompleted: 1150,
        passAccuracy: 88,
        keyPasses: 40,
        throughBalls: 10,
        longBalls: 20,
        crosses: 15,
        crossAccuracy: 25,
        dribbles: 30,
        dribblesSuccessful: 20,
        dribblesAttempted: 40,
        dribblingSuccessRate: 50,
        touches: 1800,
        touchesInBox: 200,
        tackles: 8,
        tacklesWon: 6,
        interceptions: 5,
        clearances: 10,
        blocks: 2,
        duelsWon: 110,
        duelsLost: 60,
        aerialDuelsWon: 60,
        aerialDuelsLost: 20,
        distanceCovered: 310.0,
        sprints: 260,
        topSpeed: 34.0,
        foulsCommitted: 10,
        foulsDrawn: 25,
        offsides: 15,
        penalties: 7,
        penaltiesScored: 6,
        penaltiesMissed: 1,
        bigChancesCreated: 20,
        bigChancesMissed: 10,
      },
    },
    {
      id: 10,
      name: "Robert Lewandowski",
      team: "FC Barcelona",
      position: "ST",
      age: 35,
      nationality: "Poland",
      height: "1.84m",
      weight: "80kg",
      preferredFoot: "Sağ",
      marketValue: "30M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/38253-1671435737.jpg?lm=1",
      stats: {
        goals: 18,
        assists: 8,
        matches: 28,
        minutes: 2400,
        starts: 28,
        yellowCards: 3,
        redCards: 0,
        rating: 8.2,
        shots: 100,
        shotsOnTarget: 50,
        shotsOffTarget: 40,
        shotsBlocked: 10,
        shotAccuracy: 50,
        passes: 1200,
        passesCompleted: 1050,
        passAccuracy: 88,
        keyPasses: 35,
        throughBalls: 8,
        longBalls: 15,
        crosses: 12,
        crossAccuracy: 22,
        dribbles: 25,
        dribblesSuccessful: 15,
        dribblesAttempted: 35,
        dribblingSuccessRate: 43,
        touches: 1700,
        touchesInBox: 180,
        tackles: 7,
        tacklesWon: 5,
        interceptions: 4,
        clearances: 8,
        blocks: 1,
        duelsWon: 100,
        duelsLost: 50,
        aerialDuelsWon: 50,
        aerialDuelsLost: 15,
        distanceCovered: 290.0,
        sprints: 240,
        topSpeed: 33.0,
        foulsCommitted: 9,
        foulsDrawn: 22,
        offsides: 12,
        penalties: 6,
        penaltiesScored: 5,
        penaltiesMissed: 1,
        bigChancesCreated: 18,
        bigChancesMissed: 8,
      },
    },
    {
      id: 11,
      name: "Antoine Griezmann",
      team: "Atletico Madrid",
      position: "CAM",
      age: 32,
      nationality: "France",
      height: "1.76m",
      weight: "73kg",
      preferredFoot: "Sol",
      marketValue: "25M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/125781-1671435671.jpg?lm=1",
      stats: {
        goals: 16,
        assists: 14,
        matches: 31,
        minutes: 2600,
        starts: 30,
        yellowCards: 4,
        redCards: 0,
        rating: 8.3,
        shots: 85,
        shotsOnTarget: 45,
        shotsOffTarget: 30,
        shotsBlocked: 10,
        shotAccuracy: 53,
        passes: 1500,
        passesCompleted: 1300,
        passAccuracy: 87,
        keyPasses: 55,
        throughBalls: 15,
        longBalls: 25,
        crosses: 20,
        crossAccuracy: 30,
        dribbles: 40,
        dribblesSuccessful: 25,
        dribblesAttempted: 50,
        dribblingSuccessRate: 50,
        touches: 2000,
        touchesInBox: 130,
        tackles: 12,
        tacklesWon: 8,
        interceptions: 10,
        clearances: 6,
        blocks: 2,
        duelsWon: 110,
        duelsLost: 60,
        aerialDuelsWon: 20,
        aerialDuelsLost: 20,
        distanceCovered: 300.0,
        sprints: 250,
        topSpeed: 32.0,
        foulsCommitted: 11,
        foulsDrawn: 28,
        offsides: 8,
        penalties: 3,
        penaltiesScored: 3,
        penaltiesMissed: 0,
        bigChancesCreated: 25,
        bigChancesMissed: 7,
      },
    },
    {
      id: 12,
      name: "Vinicius Junior",
      team: "Real Madrid",
      position: "LW",
      age: 23,
      nationality: "Brazil",
      height: "1.76m",
      weight: "73kg",
      preferredFoot: "Sağ",
      marketValue: "150M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/371998-1666253994.jpg?lm=1",
      stats: {
        goals: 14,
        assists: 7,
        matches: 29,
        minutes: 2400,
        starts: 28,
        yellowCards: 5,
        redCards: 0,
        rating: 8.1,
        shots: 90,
        shotsOnTarget: 40,
        shotsOffTarget: 40,
        shotsBlocked: 10,
        shotAccuracy: 44,
        passes: 1300,
        passesCompleted: 1100,
        passAccuracy: 85,
        keyPasses: 45,
        throughBalls: 12,
        longBalls: 18,
        crosses: 22,
        crossAccuracy: 28,
        dribbles: 55,
        dribblesSuccessful: 35,
        dribblesAttempted: 65,
        dribblingSuccessRate: 54,
        touches: 1900,
        touchesInBox: 140,
        tackles: 9,
        tacklesWon: 6,
        interceptions: 7,
        clearances: 4,
        blocks: 1,
        duelsWon: 95,
        duelsLost: 55,
        aerialDuelsWon: 9,
        aerialDuelsLost: 13,
        distanceCovered: 290.0,
        sprints: 240,
        topSpeed: 32.0,
        foulsCommitted: 7,
        foulsDrawn: 28,
        offsides: 9,
        penalties: 4,
        penaltiesScored: 3,
        penaltiesMissed: 1,
        bigChancesCreated: 22,
        bigChancesMissed: 9,
      },
    },
    {
      id: 13,
      name: "Jamal Musiala",
      team: "Bayern Munich",
      position: "CAM",
      age: 20,
      nationality: "Germany",
      height: "1.80m",
      weight: "70kg",
      preferredFoot: "Sağ",
      marketValue: "110M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/589799-1666254153.jpg?lm=1",
      stats: {
        goals: 12,
        assists: 9,
        matches: 28,
        minutes: 2300,
        starts: 27,
        yellowCards: 2,
        redCards: 0,
        rating: 8.0,
        shots: 80,
        shotsOnTarget: 35,
        shotsOffTarget: 35,
        shotsBlocked: 10,
        shotAccuracy: 44,
        passes: 1200,
        passesCompleted: 1000,
        passAccuracy: 83,
        keyPasses: 40,
        throughBalls: 10,
        longBalls: 15,
        crosses: 18,
        crossAccuracy: 25,
        dribbles: 50,
        dribblesSuccessful: 30,
        dribblesAttempted: 60,
        dribblingSuccessRate: 50,
        touches: 1800,
        touchesInBox: 130,
        tackles: 8,
        tacklesWon: 5,
        interceptions: 6,
        clearances: 4,
        blocks: 1,
        duelsWon: 90,
        duelsLost: 50,
        aerialDuelsWon: 8,
        aerialDuelsLost: 12,
        distanceCovered: 280.0,
        sprints: 230,
        topSpeed: 31.0,
        foulsCommitted: 6,
        foulsDrawn: 25,
        offsides: 7,
        penalties: 2,
        penaltiesScored: 2,
        penaltiesMissed: 0,
        bigChancesCreated: 20,
        bigChancesMissed: 6,
      },
    },
    {
      id: 14,
      name: "Federico Valverde",
      team: "Real Madrid",
      position: "CM",
      age: 25,
      nationality: "Uruguay",
      height: "1.82m",
      weight: "78kg",
      preferredFoot: "Sağ",
      marketValue: "100M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/470032-1671435625.jpg?lm=1",
      stats: {
        goals: 8,
        assists: 6,
        matches: 30,
        minutes: 2500,
        starts: 29,
        yellowCards: 3,
        redCards: 0,
        rating: 7.9,
        shots: 70,
        shotsOnTarget: 30,
        shotsOffTarget: 30,
        shotsBlocked: 10,
        shotAccuracy: 43,
        passes: 1400,
        passesCompleted: 1200,
        passAccuracy: 86,
        keyPasses: 45,
        throughBalls: 12,
        longBalls: 20,
        crosses: 15,
        crossAccuracy: 25,
        dribbles: 40,
        dribblesSuccessful: 25,
        dribblesAttempted: 50,
        dribblingSuccessRate: 50,
        touches: 1900,
        touchesInBox: 130,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 12,
        clearances: 8,
        blocks: 2,
        duelsWon: 100,
        duelsLost: 50,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 300.0,
        sprints: 250,
        topSpeed: 32.0,
        foulsCommitted: 10,
        foulsDrawn: 25,
        offsides: 8,
        penalties: 1,
        penaltiesScored: 1,
        penaltiesMissed: 0,
        bigChancesCreated: 20,
        bigChancesMissed: 5,
      },
    },
    {
      id: 15,
      name: "Rodri",
      team: "Manchester City",
      position: "CDM",
      age: 27,
      nationality: "Spain",
      height: "1.91m",
      weight: "82kg",
      preferredFoot: "Sağ",
      marketValue: "90M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/391437-1666254492.jpg?lm=1",
      stats: {
        goals: 7,
        assists: 5,
        matches: 32,
        minutes: 2700,
        starts: 31,
        yellowCards: 4,
        redCards: 0,
        rating: 8.1,
        shots: 60,
        shotsOnTarget: 25,
        shotsOffTarget: 25,
        shotsBlocked: 10,
        shotAccuracy: 42,
        passes: 2000,
        passesCompleted: 1800,
        passAccuracy: 90,
        keyPasses: 40,
        throughBalls: 10,
        longBalls: 40,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 30,
        dribblesSuccessful: 20,
        dribblesAttempted: 40,
        dribblingSuccessRate: 50,
        touches: 2500,
        touchesInBox: 80,
        tackles: 20,
        tacklesWon: 15,
        interceptions: 25,
        clearances: 15,
        blocks: 5,
        duelsWon: 120,
        duelsLost: 60,
        aerialDuelsWon: 40,
        aerialDuelsLost: 20,
        distanceCovered: 320.0,
        sprints: 200,
        topSpeed: 30.0,
        foulsCommitted: 12,
        foulsDrawn: 15,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 15,
        bigChancesMissed: 3,
      },
    },
    {
      id: 16,
      name: "Joshua Kimmich",
      team: "Bayern Munich",
      position: "CDM",
      age: 28,
      nationality: "Germany",
      height: "1.76m",
      weight: "73kg",
      preferredFoot: "Sağ",
      marketValue: "75M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/228957-1666254192.jpg?lm=1",
      stats: {
        goals: 6,
        assists: 8,
        matches: 31,
        minutes: 2600,
        starts: 30,
        yellowCards: 3,
        redCards: 0,
        rating: 8.2,
        shots: 55,
        shotsOnTarget: 20,
        shotsOffTarget: 25,
        shotsBlocked: 10,
        shotAccuracy: 36,
        passes: 2100,
        passesCompleted: 1900,
        passAccuracy: 90,
        keyPasses: 50,
        throughBalls: 15,
        longBalls: 45,
        crosses: 12,
        crossAccuracy: 22,
        dribbles: 35,
        dribblesSuccessful: 22,
        dribblesAttempted: 45,
        dribblingSuccessRate: 49,
        touches: 2600,
        touchesInBox: 90,
        tackles: 22,
        tacklesWon: 16,
        interceptions: 26,
        clearances: 16,
        blocks: 6,
        duelsWon: 125,
        duelsLost: 65,
        aerialDuelsWon: 42,
        aerialDuelsLost: 22,
        distanceCovered: 325.0,
        sprints: 205,
        topSpeed: 30.5,
        foulsCommitted: 13,
        foulsDrawn: 16,
        offsides: 3,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 16,
        bigChancesMissed: 4,
      },
    },
    {
      id: 17,
      name: "Casemiro",
      team: "Manchester United",
      position: "CDM",
      age: 31,
      nationality: "Brazil",
      height: "1.85m",
      weight: "84kg",
      preferredFoot: "Sağ",
      marketValue: "30M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/131891-1671435653.jpg?lm=1",
      stats: {
        goals: 5,
        assists: 3,
        matches: 28,
        minutes: 2300,
        starts: 27,
        yellowCards: 6,
        redCards: 1,
        rating: 7.8,
        shots: 50,
        shotsOnTarget: 18,
        shotsOffTarget: 22,
        shotsBlocked: 10,
        shotAccuracy: 36,
        passes: 1500,
        passesCompleted: 1300,
        passAccuracy: 87,
        keyPasses: 30,
        throughBalls: 8,
        longBalls: 35,
        crosses: 8,
        crossAccuracy: 18,
        dribbles: 25,
        dribblesSuccessful: 15,
        dribblesAttempted: 35,
        dribblingSuccessRate: 43,
        touches: 2000,
        touchesInBox: 70,
        tackles: 25,
        tacklesWon: 18,
        interceptions: 28,
        clearances: 18,
        blocks: 7,
        duelsWon: 130,
        duelsLost: 70,
        aerialDuelsWon: 50,
        aerialDuelsLost: 25,
        distanceCovered: 310.0,
        sprints: 190,
        topSpeed: 29.0,
        foulsCommitted: 15,
        foulsDrawn: 12,
        offsides: 1,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 12,
        bigChancesMissed: 2,
      },
    },
    {
      id: 18,
      name: "Toni Kroos",
      team: "Real Madrid",
      position: "CM",
      age: 33,
      nationality: "Germany",
      height: "1.83m",
      weight: "76kg",
      preferredFoot: "Sağ",
      marketValue: "15M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/31909-1671435599.jpg?lm=1",
      stats: {
        goals: 4,
        assists: 7,
        matches: 29,
        minutes: 2400,
        starts: 28,
        yellowCards: 2,
        redCards: 0,
        rating: 8.0,
        shots: 45,
        shotsOnTarget: 15,
        shotsOffTarget: 20,
        shotsBlocked: 10,
        shotAccuracy: 33,
        passes: 2200,
        passesCompleted: 2000,
        passAccuracy: 91,
        keyPasses: 48,
        throughBalls: 14,
        longBalls: 50,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 20,
        dribblesSuccessful: 12,
        dribblesAttempted: 30,
        dribblingSuccessRate: 40,
        touches: 2700,
        touchesInBox: 85,
        tackles: 18,
        tacklesWon: 13,
        interceptions: 20,
        clearances: 14,
        blocks: 4,
        duelsWon: 115,
        duelsLost: 55,
        aerialDuelsWon: 38,
        aerialDuelsLost: 18,
        distanceCovered: 315.0,
        sprints: 195,
        topSpeed: 29.5,
        foulsCommitted: 11,
        foulsDrawn: 14,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 14,
        bigChancesMissed: 3,
      },
    },
    {
      id: 19,
      name: "Luka Modrić",
      team: "Real Madrid",
      position: "CM",
      age: 38,
      nationality: "Croatia",
      height: "1.72m",
      weight: "66kg",
      preferredFoot: "Sağ",
      marketValue: "10M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/27992-1671435577.jpg?lm=1",
      stats: {
        goals: 3,
        assists: 6,
        matches: 27,
        minutes: 2200,
        starts: 26,
        yellowCards: 1,
        redCards: 0,
        rating: 7.9,
        shots: 40,
        shotsOnTarget: 12,
        shotsOffTarget: 18,
        shotsBlocked: 10,
        shotAccuracy: 30,
        passes: 1900,
        passesCompleted: 1700,
        passAccuracy: 89,
        keyPasses: 45,
        throughBalls: 13,
        longBalls: 40,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 18,
        dribblesSuccessful: 11,
        dribblesAttempted: 28,
        dribblingSuccessRate: 39,
        touches: 2400,
        touchesInBox: 80,
        tackles: 17,
        tacklesWon: 12,
        interceptions: 19,
        clearances: 13,
        blocks: 3,
        duelsWon: 110,
        duelsLost: 50,
        aerialDuelsWon: 35,
        aerialDuelsLost: 15,
        distanceCovered: 305.0,
        sprints: 185,
        topSpeed: 28.5,
        foulsCommitted: 10,
        foulsDrawn: 13,
        offsides: 1,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 13,
        bigChancesMissed: 2,
      },
    },
    {
      id: 20,
      name: "Bernardo Silva",
      team: "Manchester City",
      position: "CAM",
      age: 29,
      nationality: "Portugal",
      height: "1.73m",
      weight: "64kg",
      preferredFoot: "Sol",
      marketValue: "80M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/182057-1666254390.jpg?lm=1",
      stats: {
        goals: 9,
        assists: 7,
        matches: 30,
        minutes: 2500,
        starts: 29,
        yellowCards: 3,
        redCards: 0,
        rating: 8.1,
        shots: 65,
        shotsOnTarget: 28,
        shotsOffTarget: 27,
        shotsBlocked: 10,
        shotAccuracy: 43,
        passes: 1600,
        passesCompleted: 1400,
        passAccuracy: 88,
        keyPasses: 42,
        throughBalls: 11,
        longBalls: 17,
        crosses: 21,
        crossAccuracy: 27,
        dribbles: 48,
        dribblesSuccessful: 31,
        dribblesAttempted: 58,
        dribblingSuccessRate: 53,
        touches: 2100,
        touchesInBox: 145,
        tackles: 16,
        tacklesWon: 11,
        interceptions: 13,
        clearances: 7,
        blocks: 2,
        duelsWon: 105,
        duelsLost: 55,
        aerialDuelsWon: 10,
        aerialDuelsLost: 14,
        distanceCovered: 305.0,
        sprints: 255,
        topSpeed: 32.5,
        foulsCommitted: 9,
        foulsDrawn: 24,
        offsides: 6,
        penalties: 1,
        penaltiesScored: 1,
        penaltiesMissed: 0,
        bigChancesCreated: 23,
        bigChancesMissed: 8,
      },
    },
    {
      id: 21,
      name: "Bruno Fernandes",
      team: "Manchester United",
      position: "CAM",
      age: 29,
      nationality: "Portugal",
      height: "1.79m",
      weight: "69kg",
      preferredFoot: "Sağ",
      marketValue: "75M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/328258-1671435559.jpg?lm=1",
      stats: {
        goals: 11,
        assists: 9,
        matches: 31,
        minutes: 2600,
        starts: 30,
        yellowCards: 5,
        redCards: 0,
        rating: 8.0,
        shots: 70,
        shotsOnTarget: 30,
        shotsOffTarget: 30,
        shotsBlocked: 10,
        shotAccuracy: 43,
        passes: 1700,
        passesCompleted: 1500,
        passAccuracy: 88,
        keyPasses: 45,
        throughBalls: 12,
        longBalls: 20,
        crosses: 25,
        crossAccuracy: 30,
        dribbles: 40,
        dribblesSuccessful: 25,
        dribblesAttempted: 50,
        dribblingSuccessRate: 50,
        touches: 2200,
        touchesInBox: 150,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 12,
        clearances: 7,
        blocks: 2,
        duelsWon: 110,
        duelsLost: 60,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 310.0,
        sprints: 260,
        topSpeed: 33.0,
        foulsCommitted: 10,
        foulsDrawn: 25,
        offsides: 7,
        penalties: 4,
        penaltiesScored: 3,
        penaltiesMissed: 1,
        bigChancesCreated: 25,
        bigChancesMissed: 7,
      },
    },
    {
      id: 22,
      name: "Martin Ødegaard",
      team: "Arsenal",
      position: "CAM",
      age: 24,
      nationality: "Norway",
      height: "1.78m",
      weight: "68kg",
      preferredFoot: "Sol",
      marketValue: "90M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/316264-1671435541.jpg?lm=1",
      stats: {
        goals: 10,
        assists: 8,
        matches: 30,
        minutes: 2500,
        starts: 29,
        yellowCards: 3,
        redCards: 0,
        rating: 8.1,
        shots: 65,
        shotsOnTarget: 28,
        shotsOffTarget: 27,
        shotsBlocked: 10,
        shotAccuracy: 43,
        passes: 1600,
        passesCompleted: 1400,
        passAccuracy: 88,
        keyPasses: 42,
        throughBalls: 11,
        longBalls: 17,
        crosses: 21,
        crossAccuracy: 27,
        dribbles: 48,
        dribblesSuccessful: 31,
        dribblesAttempted: 58,
        dribblingSuccessRate: 53,
        touches: 2100,
        touchesInBox: 145,
        tackles: 16,
        tacklesWon: 11,
        interceptions: 13,
        clearances: 7,
        blocks: 2,
        duelsWon: 105,
        duelsLost: 55,
        aerialDuelsWon: 10,
        aerialDuelsLost: 14,
        distanceCovered: 305.0,
        sprints: 255,
        topSpeed: 32.5,
        foulsCommitted: 9,
        foulsDrawn: 24,
        offsides: 6,
        penalties: 1,
        penaltiesScored: 1,
        penaltiesMissed: 0,
        bigChancesCreated: 23,
        bigChancesMissed: 8,
      },
    },
    {
      id: 23,
      name: "Declan Rice",
      team: "Arsenal",
      position: "CDM",
      age: 24,
      nationality: "England",
      height: "1.85m",
      weight: "76kg",
      preferredFoot: "Sağ",
      marketValue: "100M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/357667-1671435523.jpg?lm=1",
      stats: {
        goals: 6,
        assists: 4,
        matches: 30,
        minutes: 2500,
        starts: 29,
        yellowCards: 4,
        redCards: 0,
        rating: 7.9,
        shots: 55,
        shotsOnTarget: 22,
        shotsOffTarget: 23,
        shotsBlocked: 10,
        shotAccuracy: 40,
        passes: 1700,
        passesCompleted: 1500,
        passAccuracy: 88,
        keyPasses: 40,
        throughBalls: 10,
        longBalls: 20,
        crosses: 15,
        crossAccuracy: 25,
        dribbles: 35,
        dribblesSuccessful: 20,
        dribblesAttempted: 45,
        dribblingSuccessRate: 44,
        touches: 2200,
        touchesInBox: 150,
        tackles: 20,
        tacklesWon: 15,
        interceptions: 20,
        clearances: 10,
        blocks: 3,
        duelsWon: 115,
        duelsLost: 65,
        aerialDuelsWon: 20,
        aerialDuelsLost: 20,
        distanceCovered: 315.0,
        sprints: 265,
        topSpeed: 33.5,
        foulsCommitted: 11,
        foulsDrawn: 26,
        offsides: 8,
        penalties: 2,
        penaltiesScored: 1,
        penaltiesMissed: 1,
        bigChancesCreated: 20,
        bigChancesMissed: 6,
      },
    },
    {
      id: 24,
      name: "Alexis Mac Allister",
      team: "Liverpool",
      position: "CM",
      age: 24,
      nationality: "Argentina",
      height: "1.76m",
      weight: "72kg",
      preferredFoot: "Sağ",
      marketValue: "65M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/480754-1671435505.jpg?lm=1",
      stats: {
        goals: 5,
        assists: 6,
        matches: 29,
        minutes: 2400,
        starts: 28,
        yellowCards: 3,
        redCards: 0,
        rating: 7.8,
        shots: 50,
        shotsOnTarget: 20,
        shotsOffTarget: 20,
        shotsBlocked: 10,
        shotAccuracy: 40,
        passes: 1600,
        passesCompleted: 1400,
        passAccuracy: 88,
        keyPasses: 38,
        throughBalls: 9,
        longBalls: 19,
        crosses: 14,
        crossAccuracy: 24,
        dribbles: 34,
        dribblesSuccessful: 19,
        dribblesAttempted: 44,
        dribblingSuccessRate: 43,
        touches: 2100,
        touchesInBox: 140,
        tackles: 19,
        tacklesWon: 14,
        interceptions: 19,
        clearances: 9,
        blocks: 2,
        duelsWon: 110,
        duelsLost: 60,
        aerialDuelsWon: 19,
        aerialDuelsLost: 19,
        distanceCovered: 310.0,
        sprints: 260,
        topSpeed: 33.0,
        foulsCommitted: 10,
        foulsDrawn: 25,
        offsides: 7,
        penalties: 1,
        penaltiesScored: 0,
        penaltiesMissed: 1,
        bigChancesCreated: 19,
        bigChancesMissed: 5,
      },
    },
    {
      id: 25,
      name: "Enzo Fernández",
      team: "Chelsea",
      position: "CM",
      age: 22,
      nationality: "Argentina",
      height: "1.78m",
      weight: "70kg",
      preferredFoot: "Sağ",
      marketValue: "80M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/753429-1671435487.jpg?lm=1",
      stats: {
        goals: 4,
        assists: 5,
        matches: 28,
        minutes: 2300,
        starts: 27,
        yellowCards: 4,
        redCards: 0,
        rating: 7.7,
        shots: 45,
        shotsOnTarget: 18,
        shotsOffTarget: 17,
        shotsBlocked: 10,
        shotAccuracy: 40,
        passes: 1500,
        passesCompleted: 1300,
        passAccuracy: 87,
        keyPasses: 35,
        throughBalls: 8,
        longBalls: 18,
        crosses: 13,
        crossAccuracy: 23,
        dribbles: 33,
        dribblesSuccessful: 18,
        dribblesAttempted: 43,
        dribblingSuccessRate: 42,
        touches: 2000,
        touchesInBox: 130,
        tackles: 18,
        tacklesWon: 13,
        interceptions: 18,
        clearances: 8,
        blocks: 1,
        duelsWon: 105,
        duelsLost: 55,
        aerialDuelsWon: 18,
        aerialDuelsLost: 18,
        distanceCovered: 305.0,
        sprints: 255,
        topSpeed: 32.5,
        foulsCommitted: 9,
        foulsDrawn: 24,
        offsides: 6,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 18,
        bigChancesMissed: 4,
      },
    },
    {
      id: 26,
      name: "Frenkie de Jong",
      team: "FC Barcelona",
      position: "CM",
      age: 26,
      nationality: "Netherlands",
      height: "1.81m",
      weight: "74kg",
      preferredFoot: "Sağ",
      marketValue: "75M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/326031-1666253873.jpg?lm=1",
      stats: {
        goals: 3,
        assists: 4,
        matches: 27,
        minutes: 2200,
        starts: 26,
        yellowCards: 2,
        redCards: 0,
        rating: 7.8,
        shots: 40,
        shotsOnTarget: 15,
        shotsOffTarget: 15,
        shotsBlocked: 10,
        shotAccuracy: 38,
        passes: 1500,
        passesCompleted: 1300,
        passAccuracy: 87,
        keyPasses: 35,
        throughBalls: 8,
        longBalls: 18,
        crosses: 13,
        crossAccuracy: 23,
        dribbles: 33,
        dribblesSuccessful: 18,
        dribblesAttempted: 43,
        dribblingSuccessRate: 42,
        touches: 2000,
        touchesInBox: 130,
        tackles: 18,
        tacklesWon: 13,
        interceptions: 18,
        clearances: 8,
        blocks: 1,
        duelsWon: 105,
        duelsLost: 55,
        aerialDuelsWon: 18,
        aerialDuelsLost: 18,
        distanceCovered: 305.0,
        sprints: 255,
        topSpeed: 32.5,
        foulsCommitted: 9,
        foulsDrawn: 24,
        offsides: 6,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 18,
        bigChancesMissed: 4,
      },
    },
    {
      id: 27,
      name: "Pedri",
      team: "FC Barcelona",
      position: "CM",
      age: 20,
      nationality: "Spain",
      height: "1.74m",
      weight: "61kg",
      preferredFoot: "Sağ",
      marketValue: "90M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/690135-1666253891.jpg?lm=1",
      stats: {
        goals: 4,
        assists: 5,
        matches: 26,
        minutes: 2100,
        starts: 25,
        yellowCards: 1,
        redCards: 0,
        rating: 7.9,
        shots: 42,
        shotsOnTarget: 16,
        shotsOffTarget: 16,
        shotsBlocked: 10,
        shotAccuracy: 38,
        passes: 1400,
        passesCompleted: 1200,
        passAccuracy: 86,
        keyPasses: 34,
        throughBalls: 7,
        longBalls: 17,
        crosses: 12,
        crossAccuracy: 22,
        dribbles: 32,
        dribblesSuccessful: 17,
        dribblesAttempted: 42,
        dribblingSuccessRate: 40,
        touches: 1900,
        touchesInBox: 120,
        tackles: 17,
        tacklesWon: 12,
        interceptions: 17,
        clearances: 7,
        blocks: 1,
        duelsWon: 100,
        duelsLost: 50,
        aerialDuelsWon: 17,
        aerialDuelsLost: 17,
        distanceCovered: 300.0,
        sprints: 250,
        topSpeed: 32.0,
        foulsCommitted: 8,
        foulsDrawn: 23,
        offsides: 5,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 17,
        bigChancesMissed: 3,
      },
    },
    {
      id: 28,
      name: "Gavi",
      team: "FC Barcelona",
      position: "CM",
      age: 19,
      nationality: "Spain",
      height: "1.73m",
      weight: "68kg",
      preferredFoot: "Sağ",
      marketValue: "90M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/649275-1666253909.jpg?lm=1",
      stats: {
        goals: 3,
        assists: 4,
        matches: 25,
        minutes: 2000,
        starts: 24,
        yellowCards: 3,
        redCards: 0,
        rating: 7.7,
        shots: 40,
        shotsOnTarget: 14,
        shotsOffTarget: 16,
        shotsBlocked: 10,
        shotAccuracy: 35,
        passes: 1300,
        passesCompleted: 1100,
        passAccuracy: 85,
        keyPasses: 33,
        throughBalls: 6,
        longBalls: 16,
        crosses: 11,
        crossAccuracy: 21,
        dribbles: 31,
        dribblesSuccessful: 16,
        dribblesAttempted: 41,
        dribblingSuccessRate: 39,
        touches: 1800,
        touchesInBox: 110,
        tackles: 16,
        tacklesWon: 11,
        interceptions: 16,
        clearances: 6,
        blocks: 0,
        duelsWon: 95,
        duelsLost: 45,
        aerialDuelsWon: 16,
        aerialDuelsLost: 16,
        distanceCovered: 290.0,
        sprints: 240,
        topSpeed: 31.0,
        foulsCommitted: 7,
        foulsDrawn: 22,
        offsides: 4,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 16,
        bigChancesMissed: 2,
      },
    },
    {
      id: 29,
      name: "Eduardo Camavinga",
      team: "Real Madrid",
      position: "CM",
      age: 21,
      nationality: "France",
      height: "1.82m",
      weight: "68kg",
      preferredFoot: "Sol",
      marketValue: "85M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/698414-1666253857.jpg?lm=1",
      stats: {
        goals: 2,
        assists: 3,
        matches: 26,
        minutes: 2100,
        starts: 25,
        yellowCards: 4,
        redCards: 0,
        rating: 7.6,
        shots: 38,
        shotsOnTarget: 13,
        shotsOffTarget: 15,
        shotsBlocked: 10,
        shotAccuracy: 34,
        passes: 1200,
        passesCompleted: 1000,
        passAccuracy: 83,
        keyPasses: 32,
        throughBalls: 5,
        longBalls: 15,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 30,
        dribblesSuccessful: 15,
        dribblesAttempted: 40,
        dribblingSuccessRate: 38,
        touches: 1700,
        touchesInBox: 100,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 15,
        clearances: 5,
        blocks: 0,
        duelsWon: 90,
        duelsLost: 40,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 280.0,
        sprints: 230,
        topSpeed: 30.0,
        foulsCommitted: 6,
        foulsDrawn: 21,
        offsides: 3,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 15,
        bigChancesMissed: 1,
      },
    },
    {
      id: 30,
      name: "Aurélien Tchouaméni",
      team: "Real Madrid",
      position: "CDM",
      age: 23,
      nationality: "France",
      height: "1.87m",
      weight: "81kg",
      preferredFoot: "Sağ",
      marketValue: "90M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/780358-1666253839.jpg?lm=1",
      stats: {
        goals: 1,
        assists: 2,
        matches: 25,
        minutes: 2000,
        starts: 24,
        yellowCards: 5,
        redCards: 0,
        rating: 7.5,
        shots: 35,
        shotsOnTarget: 12,
        shotsOffTarget: 13,
        shotsBlocked: 10,
        shotAccuracy: 34,
        passes: 1100,
        passesCompleted: 900,
        passAccuracy: 82,
        keyPasses: 30,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 29,
        dribblesSuccessful: 14,
        dribblesAttempted: 39,
        dribblingSuccessRate: 36,
        touches: 1600,
        touchesInBox: 90,
        tackles: 14,
        tacklesWon: 9,
        interceptions: 14,
        clearances: 4,
        blocks: 0,
        duelsWon: 85,
        duelsLost: 35,
        aerialDuelsWon: 14,
        aerialDuelsLost: 14,
        distanceCovered: 270.0,
        sprints: 220,
        topSpeed: 29.0,
        foulsCommitted: 5,
        foulsDrawn: 20,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 14,
        bigChancesMissed: 0,
      },
    },
    {
      id: 31,
      name: "N'Golo Kanté",
      team: "Al-Ittihad",
      position: "CDM",
      age: 32,
      nationality: "France",
      height: "1.68m",
      weight: "68kg",
      preferredFoot: "Sağ",
      marketValue: "10M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/182589-1671435469.jpg?lm=1",
      stats: {
        goals: 0,
        assists: 1,
        matches: 20,
        minutes: 1600,
        starts: 19,
        yellowCards: 2,
        redCards: 0,
        rating: 7.4,
        shots: 30,
        shotsOnTarget: 10,
        shotsOffTarget: 10,
        shotsBlocked: 10,
        shotAccuracy: 33,
        passes: 900,
        passesCompleted: 700,
        passAccuracy: 78,
        keyPasses: 25,
        throughBalls: 3,
        longBalls: 13,
        crosses: 8,
        crossAccuracy: 18,
        dribbles: 28,
        dribblesSuccessful: 13,
        dribblesAttempted: 38,
        dribblingSuccessRate: 34,
        touches: 1400,
        touchesInBox: 80,
        tackles: 13,
        tacklesWon: 8,
        interceptions: 13,
        clearances: 3,
        blocks: 0,
        duelsWon: 80,
        duelsLost: 30,
        aerialDuelsWon: 13,
        aerialDuelsLost: 13,
        distanceCovered: 260.0,
        sprints: 210,
        topSpeed: 28.0,
        foulsCommitted: 4,
        foulsDrawn: 19,
        offsides: 1,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 13,
        bigChancesMissed: 0,
      },
    },
    {
      id: 32,
      name: "Marco Verratti",
      team: "Al-Arabi SC",
      position: "CM",
      age: 31,
      nationality: "Italy",
      height: "1.65m",
      weight: "60kg",
      preferredFoot: "Sağ",
      marketValue: "15M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/102581-1671435451.jpg?lm=1",
      stats: {
        goals: 0,
        assists: 2,
        matches: 22,
        minutes: 1800,
        starts: 21,
        yellowCards: 3,
        redCards: 0,
        rating: 7.6,
        shots: 32,
        shotsOnTarget: 11,
        shotsOffTarget: 11,
        shotsBlocked: 10,
        shotAccuracy: 34,
        passes: 1000,
        passesCompleted: 800,
        passAccuracy: 80,
        keyPasses: 27,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 27,
        dribblesSuccessful: 12,
        dribblesAttempted: 37,
        dribblingSuccessRate: 32,
        touches: 1500,
        touchesInBox: 85,
        tackles: 12,
        tacklesWon: 7,
        interceptions: 12,
        clearances: 2,
        blocks: 0,
        duelsWon: 75,
        duelsLost: 25,
        aerialDuelsWon: 12,
        aerialDuelsLost: 12,
        distanceCovered: 250.0,
        sprints: 200,
        topSpeed: 27.0,
        foulsCommitted: 3,
        foulsDrawn: 18,
        offsides: 0,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 12,
        bigChancesMissed: 0,
      },
    },
    {
      id: 33,
      name: "Thiago Alcântara",
      team: "Liverpool",
      position: "CM",
      age: 32,
      nationality: "Spain",
      height: "1.74m",
      weight: "70kg",
      preferredFoot: "Sağ",
      marketValue: "15M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/101422-1671435433.jpg?lm=1",
      stats: {
        goals: 0,
        assists: 1,
        matches: 18,
        minutes: 1500,
        starts: 17,
        yellowCards: 1,
        redCards: 0,
        rating: 7.5,
        shots: 28,
        shotsOnTarget: 9,
        shotsOffTarget: 9,
        shotsBlocked: 10,
        shotAccuracy: 32,
        passes: 800,
        passesCompleted: 600,
        passAccuracy: 75,
        keyPasses: 23,
        throughBalls: 2,
        longBalls: 12,
        crosses: 7,
        crossAccuracy: 17,
        dribbles: 26,
        dribblesSuccessful: 11,
        dribblesAttempted: 36,
        dribblingSuccessRate: 30,
        touches: 1300,
        touchesInBox: 75,
        tackles: 11,
        tacklesWon: 6,
        interceptions: 11,
        clearances: 1,
        blocks: 0,
        duelsWon: 70,
        duelsLost: 20,
        aerialDuelsWon: 11,
        aerialDuelsLost: 11,
        distanceCovered: 240.0,
        sprints: 190,
        topSpeed: 26.0,
        foulsCommitted: 2,
        foulsDrawn: 17,
        offsides: 0,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 11,
        bigChancesMissed: 0,
      },
    },
    {
      id: 34,
      name: "Thomas Müller",
      team: "Bayern Munich",
      position: "CAM",
      age: 34,
      nationality: "Germany",
      height: "1.86m",
      weight: "75kg",
      preferredFoot: "Sağ",
      marketValue: "12M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/56141-1671435415.jpg?lm=1",
      stats: {
        goals: 2,
        assists: 5,
        matches: 24,
        minutes: 1900,
        starts: 23,
        yellowCards: 0,
        redCards: 0,
        rating: 7.7,
        shots: 34,
        shotsOnTarget: 12,
        shotsOffTarget: 12,
        shotsBlocked: 10,
        shotAccuracy: 35,
        passes: 1100,
        passesCompleted: 900,
        passAccuracy: 82,
        keyPasses: 30,
        throughBalls: 5,
        longBalls: 15,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 29,
        dribblesSuccessful: 14,
        dribblesAttempted: 39,
        dribblingSuccessRate: 37,
        touches: 1600,
        touchesInBox: 90,
        tackles: 14,
        tacklesWon: 9,
        interceptions: 14,
        clearances: 4,
        blocks: 0,
        duelsWon: 85,
        duelsLost: 35,
        aerialDuelsWon: 14,
        aerialDuelsLost: 14,
        distanceCovered: 270.0,
        sprints: 220,
        topSpeed: 29.0,
        foulsCommitted: 5,
        foulsDrawn: 20,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 14,
        bigChancesMissed: 0,
      },
    },
    {
      id: 35,
      name: "Christian Eriksen",
      team: "Manchester United",
      position: "CM",
      age: 31,
      nationality: "Denmark",
      height: "1.82m",
      weight: "76kg",
      preferredFoot: "Both",
      marketValue: "18M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/42149-1671435397.jpg?lm=1",
      stats: {
        goals: 1,
        assists: 3,
        matches: 23,
        minutes: 1800,
        starts: 22,
        yellowCards: 2,
        redCards: 0,
        rating: 7.6,
        shots: 33,
        shotsOnTarget: 11,
        shotsOffTarget: 11,
        shotsBlocked: 11,
        shotAccuracy: 33,
        passes: 1000,
        passesCompleted: 800,
        passAccuracy: 80,
        keyPasses: 28,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 28,
        dribblesSuccessful: 13,
        dribblesAttempted: 38,
        dribblingSuccessRate: 35,
        touches: 1500,
        touchesInBox: 80,
        tackles: 13,
        tacklesWon: 8,
        interceptions: 13,
        clearances: 3,
        blocks: 0,
        duelsWon: 80,
        duelsLost: 30,
        aerialDuelsWon: 13,
        aerialDuelsLost: 13,
        distanceCovered: 260.0,
        sprints: 210,
        topSpeed: 28.0,
        foulsCommitted: 4,
        foulsDrawn: 19,
        offsides: 1,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 13,
        bigChancesMissed: 0,
      },
    },
    {
      id: 36,
      name: "James Maddison",
      team: "Tottenham Hotspur",
      position: "CAM",
      age: 27,
      nationality: "England",
      height: "1.75m",
      weight: "73kg",
      preferredFoot: "Sağ",
      marketValue: "60M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/314273-1671435379.jpg?lm=1",
      stats: {
        goals: 7,
        assists: 6,
        matches: 26,
        minutes: 2100,
        starts: 25,
        yellowCards: 3,
        redCards: 0,
        rating: 7.9,
        shots: 55,
        shotsOnTarget: 20,
        shotsOffTarget: 25,
        shotsBlocked: 10,
        shotAccuracy: 36,
        passes: 1200,
        passesCompleted: 1000,
        passAccuracy: 83,
        keyPasses: 32,
        throughBalls: 5,
        longBalls: 15,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 30,
        dribblesSuccessful: 15,
        dribblesAttempted: 40,
        dribblingSuccessRate: 38,
        touches: 1700,
        touchesInBox: 100,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 15,
        clearances: 5,
        blocks: 0,
        duelsWon: 90,
        duelsLost: 40,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 280.0,
        sprints: 230,
        topSpeed: 30.0,
        foulsCommitted: 6,
        foulsDrawn: 21,
        offsides: 3,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 15,
        bigChancesMissed: 1,
      },
    },
    {
      id: 37,
      name: "Jack Grealish",
      team: "Manchester City",
      position: "LW",
      age: 28,
      nationality: "England",
      height: "1.80m",
      weight: "76kg",
      preferredFoot: "Sağ",
      marketValue: "70M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/183284-1666254354.jpg?lm=1",
      stats: {
        goals: 5,
        assists: 4,
        matches: 25,
        minutes: 2000,
        starts: 24,
        yellowCards: 2,
        redCards: 0,
        rating: 7.8,
        shots: 45,
        shotsOnTarget: 15,
        shotsOffTarget: 20,
        shotsBlocked: 10,
        shotAccuracy: 33,
        passes: 1100,
        passesCompleted: 900,
        passAccuracy: 82,
        keyPasses: 30,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 29,
        dribblesSuccessful: 14,
        dribblesAttempted: 39,
        dribblingSuccessRate: 36,
        touches: 1600,
        touchesInBox: 90,
        tackles: 14,
        tacklesWon: 9,
        interceptions: 14,
        clearances: 4,
        blocks: 0,
        duelsWon: 85,
        duelsLost: 35,
        aerialDuelsWon: 14,
        aerialDuelsLost: 14,
        distanceCovered: 270.0,
        sprints: 220,
        topSpeed: 29.0,
        foulsCommitted: 5,
        foulsDrawn: 20,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 14,
        bigChancesMissed: 0,
      },
    },
    {
      id: 38,
      name: "Marcus Rashford",
      team: "Manchester United",
      position: "LW",
      age: 26,
      nationality: "England",
      height: "1.85m",
      weight: "70kg",
      preferredFoot: "Sağ",
      marketValue: "60M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/258455-1671435361.jpg?lm=1",
      stats: {
        goals: 6,
        assists: 3,
        matches: 24,
        minutes: 1900,
        starts: 23,
        yellowCards: 1,
        redCards: 0,
        rating: 7.7,
        shots: 50,
        shotsOnTarget: 18,
        shotsOffTarget: 22,
        shotsBlocked: 10,
        shotAccuracy: 36,
        passes: 1000,
        passesCompleted: 800,
        passAccuracy: 80,
        keyPasses: 28,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 28,
        dribblesSuccessful: 13,
        dribblesAttempted: 38,
        dribblingSuccessRate: 35,
        touches: 1500,
        touchesInBox: 80,
        tackles: 13,
        tacklesWon: 8,
        interceptions: 13,
        clearances: 3,
        blocks: 0,
        duelsWon: 80,
        duelsLost: 30,
        aerialDuelsWon: 13,
        aerialDuelsLost: 13,
        distanceCovered: 260.0,
        sprints: 210,
        topSpeed: 28.0,
        foulsCommitted: 4,
        foulsDrawn: 19,
        offsides: 1,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 13,
        bigChancesMissed: 0,
      },
    },
    {
      id: 39,
      name: "Raheem Sterling",
      team: "Chelsea",
      position: "RW",
      age: 29,
      nationality: "England",
      height: "1.70m",
      weight: "69kg",
      preferredFoot: "Sağ",
      marketValue: "50M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/134429-1671435343.jpg?lm=1",
      stats: {
        goals: 5,
        assists: 2,
        matches: 23,
        minutes: 1800,
        starts: 22,
        yellowCards: 2,
        redCards: 0,
        rating: 7.6,
        shots: 40,
        shotsOnTarget: 14,
        shotsOffTarget: 16,
        shotsBlocked: 10,
        shotAccuracy: 35,
        passes: 900,
        passesCompleted: 700,
        passAccuracy: 78,
        keyPasses: 25,
        throughBalls: 3,
        longBalls: 13,
        crosses: 8,
        crossAccuracy: 18,
        dribbles: 28,
        dribblesSuccessful: 13,
        dribblesAttempted: 38,
        dribblingSuccessRate: 34,
        touches: 1400,
        touchesInBox: 80,
        tackles: 13,
        tacklesWon: 8,
        interceptions: 13,
        clearances: 3,
        blocks: 0,
        duelsWon: 80,
        duelsLost: 30,
        aerialDuelsWon: 13,
        aerialDuelsLost: 13,
        distanceCovered: 260.0,
        sprints: 210,
        topSpeed: 28.0,
        foulsCommitted: 4,
        foulsDrawn: 19,
        offsides: 1,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 13,
        bigChancesMissed: 0,
      },
    },
    {
      id: 40,
      name: "Bukayo Saka",
      team: "Arsenal",
      position: "RW",
      age: 22,
      nationality: "England",
      height: "1.78m",
      weight: "65kg",
      preferredFoot: "Sol",
      marketValue: "120M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/441754-1671435325.jpg?lm=1",
      stats: {
        goals: 10,
        assists: 7,
        matches: 28,
        minutes: 2300,
        starts: 27,
        yellowCards: 3,
        redCards: 0,
        rating: 8.0,
        shots: 60,
        shotsOnTarget: 22,
        shotsOffTarget: 28,
        shotsBlocked: 10,
        shotAccuracy: 37,
        passes: 1300,
        passesCompleted: 1100,
        passAccuracy: 85,
        keyPasses: 35,
        throughBalls: 6,
        longBalls: 16,
        crosses: 11,
        crossAccuracy: 21,
        dribbles: 31,
        dribblesSuccessful: 16,
        dribblesAttempted: 41,
        dribblingSuccessRate: 39,
        touches: 1800,
        touchesInBox: 110,
        tackles: 16,
        tacklesWon: 11,
        interceptions: 16,
        clearances: 6,
        blocks: 0,
        duelsWon: 95,
        duelsLost: 45,
        aerialDuelsWon: 16,
        aerialDuelsLost: 16,
        distanceCovered: 290.0,
        sprints: 240,
        topSpeed: 31.0,
        foulsCommitted: 7,
        foulsDrawn: 22,
        offsides: 4,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 16,
        bigChancesMissed: 2,
      },
    },
    {
      id: 41,
      name: "Gabriel Martinelli",
      team: "Arsenal",
      position: "LW",
      age: 22,
      nationality: "Brazil",
      height: "1.78m",
      weight: "70kg",
      preferredFoot: "Sağ",
      marketValue: "80M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/538303-1671435307.jpg?lm=1",
      stats: {
        goals: 9,
        assists: 5,
        matches: 27,
        minutes: 2200,
        starts: 26,
        yellowCards: 2,
        redCards: 0,
        rating: 7.9,
        shots: 55,
        shotsOnTarget: 20,
        shotsOffTarget: 25,
        shotsBlocked: 10,
        shotAccuracy: 36,
        passes: 1200,
        passesCompleted: 1000,
        passAccuracy: 83,
        keyPasses: 32,
        throughBalls: 5,
        longBalls: 15,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 30,
        dribblesSuccessful: 15,
        dribblesAttempted: 40,
        dribblingSuccessRate: 38,
        touches: 1700,
        touchesInBox: 100,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 15,
        clearances: 5,
        blocks: 0,
        duelsWon: 90,
        duelsLost: 40,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 280.0,
        sprints: 230,
        topSpeed: 30.0,
        foulsCommitted: 6,
        foulsDrawn: 21,
        offsides: 3,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 15,
        bigChancesMissed: 1,
      },
    },
    {
      id: 42,
      name: "Phil Foden",
      team: "Manchester City",
      position: "CAM",
      age: 23,
      nationality: "England",
      height: "1.71m",
      weight: "69kg",
      preferredFoot: "Sol",
      marketValue: "110M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/406634-1666254336.jpg?lm=1",
      stats: {
        goals: 8,
        assists: 6,
        matches: 26,
        minutes: 2100,
        starts: 25,
        yellowCards: 3,
        redCards: 0,
        rating: 8.0,
        shots: 55,
        shotsOnTarget: 20,
        shotsOffTarget: 25,
        shotsBlocked: 10,
        shotAccuracy: 36,
        passes: 1200,
        passesCompleted: 1000,
        passAccuracy: 83,
        keyPasses: 32,
        throughBalls: 5,
        longBalls: 15,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 30,
        dribblesSuccessful: 15,
        dribblesAttempted: 40,
        dribblingSuccessRate: 38,
        touches: 1700,
        touchesInBox: 100,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 15,
        clearances: 5,
        blocks: 0,
        duelsWon: 90,
        duelsLost: 40,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 280.0,
        sprints: 230,
        topSpeed: 30.0,
        foulsCommitted: 6,
        foulsDrawn: 21,
        offsides: 3,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 15,
        bigChancesMissed: 1,
      },
    },
    {
      id: 43,
      name: "Christopher Nkunku",
      team: "Chelsea",
      position: "CAM",
      age: 26,
      nationality: "France",
      height: "1.75m",
      weight: "73kg",
      preferredFoot: "Both",
      marketValue: "70M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/344259-1671435289.jpg?lm=1",
      stats: {
        goals: 6,
        assists: 5,
        matches: 25,
        minutes: 2000,
        starts: 24,
        yellowCards: 2,
        redCards: 0,
        rating: 7.8,
        shots: 45,
        shotsOnTarget: 15,
        shotsOffTarget: 20,
        shotsBlocked: 10,
        shotAccuracy: 33,
        passes: 1100,
        passesCompleted: 900,
        passAccuracy: 82,
        keyPasses: 30,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 29,
        dribblesSuccessful: 14,
        dribblesAttempted: 39,
        dribblingSuccessRate: 36,
        touches: 1600,
        touchesInBox: 90,
        tackles: 14,
        tacklesWon: 9,
        interceptions: 14,
        clearances: 4,
        blocks: 0,
        duelsWon: 85,
        duelsLost: 35,
        aerialDuelsWon: 14,
        aerialDuelsLost: 14,
        distanceCovered: 270.0,
        sprints: 220,
        topSpeed: 29.0,
        foulsCommitted: 5,
        foulsDrawn: 20,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 14,
        bigChancesMissed: 0,
      },
    },
    {
      id: 44,
      name: "Darwin Núñez",
      team: "Liverpool",
      position: "ST",
      age: 24,
      nationality: "Uruguay",
      height: "1.87m",
      weight: "81kg",
      preferredFoot: "Sağ",
      marketValue: "70M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/631729-1666254259.jpg?lm=1",
      stats: {
        goals: 12,
        assists: 7,
        matches: 30,
        minutes: 2500,
        starts: 29,
        yellowCards: 3,
        redCards: 0,
        rating: 7.9,
        shots: 70,
        shotsOnTarget: 30,
        shotsOffTarget: 30,
        shotsBlocked: 10,
        shotAccuracy: 43,
        passes: 1400,
        passesCompleted: 1200,
        passAccuracy: 86,
        keyPasses: 45,
        throughBalls: 12,
        longBalls: 20,
        crosses: 15,
        crossAccuracy: 25,
        dribbles: 40,
        dribblesSuccessful: 25,
        dribblesAttempted: 50,
        dribblingSuccessRate: 50,
        touches: 1900,
        touchesInBox: 130,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 12,
        clearances: 8,
        blocks: 2,
        duelsWon: 100,
        duelsLost: 50,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 300.0,
        sprints: 250,
        topSpeed: 32.0,
        foulsCommitted: 10,
        foulsDrawn: 25,
        offsides: 8,
        penalties: 1,
        penaltiesScored: 1,
        penaltiesMissed: 0,
        bigChancesCreated: 20,
        bigChancesMissed: 5,
      },
    },
    {
      id: 45,
      name: "Richarlison",
      team: "Tottenham Hotspur",
      position: "ST",
      age: 26,
      nationality: "Brazil",
      height: "1.79m",
      weight: "71kg",
      preferredFoot: "Sağ",
      marketValue: "45M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/352089-1671435271.jpg?lm=1",
      stats: {
        goals: 8,
        assists: 4,
        matches: 28,
        minutes: 2300,
        starts: 27,
        yellowCards: 3,
        redCards: 0,
        rating: 7.8,
        shots: 50,
        shotsOnTarget: 20,
        shotsOffTarget: 20,
        shotsBlocked: 10,
        shotAccuracy: 40,
        passes: 1100,
        passesCompleted: 900,
        passAccuracy: 82,
        keyPasses: 30,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 29,
        dribblesSuccessful: 14,
        dribblesAttempted: 39,
        dribblingSuccessRate: 36,
        touches: 1600,
        touchesInBox: 90,
        tackles: 14,
        tacklesWon: 9,
        interceptions: 14,
        clearances: 4,
        blocks: 0,
        duelsWon: 85,
        duelsLost: 35,
        aerialDuelsWon: 14,
        aerialDuelsLost: 14,
        distanceCovered: 270.0,
        sprints: 220,
        topSpeed: 29.0,
        foulsCommitted: 5,
        foulsDrawn: 20,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 14,
        bigChancesMissed: 0,
      },
    },
    {
      id: 46,
      name: "Alexander Isak",
      team: "Newcastle United",
      position: "ST",
      age: 24,
      nationality: "Sweden",
      height: "1.92m",
      weight: "76kg",
      preferredFoot: "Both",
      marketValue: "70M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/349066-1671435253.jpg?lm=1",
      stats: {
        goals: 11,
        assists: 6,
        matches: 29,
        minutes: 2400,
        starts: 28,
        yellowCards: 3,
        redCards: 0,
        rating: 7.9,
        shots: 60,
        shotsOnTarget: 22,
        shotsOffTarget: 28,
        shotsBlocked: 10,
        shotAccuracy: 37,
        passes: 1300,
        passesCompleted: 1100,
        passAccuracy: 85,
        keyPasses: 35,
        throughBalls: 6,
        longBalls: 16,
        crosses: 11,
        crossAccuracy: 21,
        dribbles: 31,
        dribblesSuccessful: 16,
        dribblesAttempted: 41,
        dribblingSuccessRate: 39,
        touches: 1800,
        touchesInBox: 110,
        tackles: 16,
        tacklesWon: 11,
        interceptions: 16,
        clearances: 6,
        blocks: 0,
        duelsWon: 95,
        duelsLost: 45,
        aerialDuelsWon: 16,
        aerialDuelsLost: 16,
        distanceCovered: 290.0,
        sprints: 240,
        topSpeed: 31.0,
        foulsCommitted: 7,
        foulsDrawn: 22,
        offsides: 4,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 16,
        bigChancesMissed: 2,
      },
    },
    {
      id: 47,
      name: "Callum Wilson",
      team: "Newcastle United",
      position: "ST",
      age: 31,
      nationality: "England",
      height: "1.80m",
      weight: "74kg",
      preferredFoot: "Sağ",
      marketValue: "18M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/128898-1671435235.jpg?lm=1",
      stats: {
        goals: 9,
        assists: 5,
        matches: 27,
        minutes: 2200,
        starts: 26,
        yellowCards: 2,
        redCards: 0,
        rating: 7.8,
        shots: 55,
        shotsOnTarget: 20,
        shotsOffTarget: 25,
        shotsBlocked: 10,
        shotAccuracy: 36,
        passes: 1200,
        passesCompleted: 1000,
        passAccuracy: 83,
        keyPasses: 32,
        throughBalls: 5,
        longBalls: 15,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 30,
        dribblesSuccessful: 15,
        dribblesAttempted: 40,
        dribblingSuccessRate: 38,
        touches: 1700,
        touchesInBox: 100,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 15,
        clearances: 5,
        blocks: 0,
        duelsWon: 90,
        duelsLost: 40,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 280.0,
        sprints: 230,
        topSpeed: 30.0,
        foulsCommitted: 6,
        foulsDrawn: 21,
        offsides: 3,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 15,
        bigChancesMissed: 1,
      },
    },
    {
      id: 48,
      name: "Dominic Calvert-Lewin",
      team: "Everton",
      position: "ST",
      age: 26,
      nationality: "England",
      height: "1.87m",
      weight: "72kg",
      preferredFoot: "Sağ",
      marketValue: "22M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/306559-1671435217.jpg?lm=1",
      stats: {
        goals: 7,
        assists: 4,
        matches: 26,
        minutes: 2100,
        starts: 25,
        yellowCards: 3,
        redCards: 0,
        rating: 7.7,
        shots: 45,
        shotsOnTarget: 15,
        shotsOffTarget: 20,
        shotsBlocked: 10,
        shotAccuracy: 33,
        passes: 1100,
        passesCompleted: 900,
        passAccuracy: 82,
        keyPasses: 30,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 29,
        dribblesSuccessful: 14,
        dribblesAttempted: 39,
        dribblingSuccessRate: 36,
        touches: 1600,
        touchesInBox: 90,
        tackles: 14,
        tacklesWon: 9,
        interceptions: 14,
        clearances: 4,
        blocks: 0,
        duelsWon: 85,
        duelsLost: 35,
        aerialDuelsWon: 14,
        aerialDuelsLost: 14,
        distanceCovered: 270.0,
        sprints: 220,
        topSpeed: 29.0,
        foulsCommitted: 5,
        foulsDrawn: 20,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 14,
        bigChancesMissed: 0,
      },
    },
    {
      id: 49,
      name: "Ivan Toney",
      team: "Brentford",
      position: "ST",
      age: 27,
      nationality: "England",
      height: "1.85m",
      weight: "77kg",
      preferredFoot: "Sağ",
      marketValue: "50M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/342707-1671435199.jpg?lm=1",
      stats: {
        goals: 10,
        assists: 6,
        matches: 28,
        minutes: 2300,
        starts: 27,
        yellowCards: 3,
        redCards: 0,
        rating: 7.8,
        shots: 55,
        shotsOnTarget: 20,
        shotsOffTarget: 25,
        shotsBlocked: 10,
        shotAccuracy: 36,
        passes: 1200,
        passesCompleted: 1000,
        passAccuracy: 83,
        keyPasses: 32,
        throughBalls: 5,
        longBalls: 15,
        crosses: 10,
        crossAccuracy: 20,
        dribbles: 30,
        dribblesSuccessful: 15,
        dribblesAttempted: 40,
        dribblingSuccessRate: 38,
        touches: 1700,
        touchesInBox: 100,
        tackles: 15,
        tacklesWon: 10,
        interceptions: 15,
        clearances: 5,
        blocks: 0,
        duelsWon: 90,
        duelsLost: 40,
        aerialDuelsWon: 15,
        aerialDuelsLost: 15,
        distanceCovered: 280.0,
        sprints: 230,
        topSpeed: 30.0,
        foulsCommitted: 6,
        foulsDrawn: 21,
        offsides: 3,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 15,
        bigChancesMissed: 1,
      },
    },
    {
      id: 50,
      name: "Ollie Watkins",
      team: "Aston Villa",
      position: "ST",
      age: 27,
      nationality: "England",
      height: "1.80m",
      weight: "76kg",
      preferredFoot: "Sağ",
      marketValue: "40M€",
      image: "https://img.a.transfermarkt.technology/portrait/header/317327-1671435181.jpg?lm=1",
      stats: {
        goals: 8,
        assists: 5,
        matches: 26,
        minutes: 2100,
        starts: 25,
        yellowCards: 3,
        redCards: 0,
        rating: 7.7,
        shots: 45,
        shotsOnTarget: 15,
        shotsOffTarget: 20,
        shotsBlocked: 10,
        shotAccuracy: 33,
        passes: 1100,
        passesCompleted: 900,
        passAccuracy: 82,
        keyPasses: 30,
        throughBalls: 4,
        longBalls: 14,
        crosses: 9,
        crossAccuracy: 19,
        dribbles: 29,
        dribblesSuccessful: 14,
        dribblesAttempted: 39,
        dribblingSuccessRate: 36,
        touches: 1600,
        touchesInBox: 90,
        tackles: 14,
        tacklesWon: 9,
        interceptions: 14,
        clearances: 4,
        blocks: 0,
        duelsWon: 85,
        duelsLost: 35,
        aerialDuelsWon: 14,
        aerialDuelsLost: 14,
        distanceCovered: 270.0,
        sprints: 220,
        topSpeed: 29.0,
        foulsCommitted: 5,
        foulsDrawn: 20,
        offsides: 2,
        penalties: 0,
        penaltiesScored: 0,
        penaltiesMissed: 0,
        bigChancesCreated: 14,
        bigChancesMissed: 0,
      },
    },
  ]

  const getPositionColor = (position: string) => {
    switch (position) {
      case "ST":
        return "bg-gradient-to-r from-red-500 to-red-600 text-white"
      case "RW":
      case "LW":
        return "bg-gradient-to-r from-blue-500 to-blue-600 text-white"
      case "CAM":
      case "CM":
        return "bg-gradient-to-r from-green-500 to-green-600 text-white"
      case "CB":
        return "bg-gradient-to-r from-purple-500 to-purple-600 text-white"
      default:
        return "bg-gradient-to-r from-gray-500 to-gray-600 text-white"
    }
  }

  const handleComparePlayer = (playerId: number) => {
    if (comparisonPlayers.length === 0) {
      setComparisonPlayers([playerId])
    } else if (comparisonPlayers.length === 1 && !comparisonPlayers.includes(playerId)) {
      setComparisonPlayers([...comparisonPlayers, playerId])
      setShowComparison(true)
    } else if (comparisonPlayers.includes(playerId)) {
      setComparisonPlayers(comparisonPlayers.filter((id) => id !== playerId))
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 text-white">
      {/* Animated Background */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-blue-500/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-emerald-500/5 rounded-full blur-3xl animate-pulse delay-2000"></div>
      </div>
      {/* Modern Dark Header */}
      <header className="bg-white/5 backdrop-blur-xl border-b border-white/10 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div className="w-12 h-12 bg-gradient-to-r from-emerald-400 to-cyan-400 rounded-2xl flex items-center justify-center">
                <Star className="w-7 h-7 text-black" />
              </div>
              <div>
                <h1 className="text-3xl font-black bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">
                  FUTBOL STATS
                </h1>
                <p className="text-sm text-gray-400">Profesyonel Oyuncu Analizi</p>
              </div>
            </div>

            <div className="flex items-center space-x-4">
              <div className="relative">
                <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
                <Input
                  type="text"
                  placeholder="Oyuncu ara..."
                  className="pl-12 w-96 bg-white/10 border-white/20 text-white placeholder-gray-300 focus:border-emerald-400 focus:ring-emerald-400/20 h-12 rounded-xl backdrop-blur-sm"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                />
              </div>

              <div className="flex items-center bg-white/10 backdrop-blur-sm rounded-xl p-1">
                <Button
                  variant={viewMode === "grid" ? "default" : "ghost"}
                  size="sm"
                  onClick={() => setViewMode("grid")}
                  className={
                    viewMode === "grid" ? "bg-emerald-500 hover:bg-emerald-600" : "text-gray-400 hover:text-white"
                  }
                >
                  <Grid className="w-4 h-4" />
                </Button>
                <Button
                  variant={viewMode === "list" ? "default" : "ghost"}
                  size="sm"
                  onClick={() => setViewMode("list")}
                  className={
                    viewMode === "list" ? "bg-emerald-500 hover:bg-emerald-600" : "text-gray-400 hover:text-white"
                  }
                >
                  <List className="w-4 h-4" />
                </Button>
              </div>

              <Button
                variant="outline"
                className="border-white/20 text-gray-300 hover:bg-white/10 bg-transparent backdrop-blur-sm"
              >
                <Filter className="w-4 h-4 mr-2" />
                Filtrele
              </Button>
              {comparisonPlayers.length > 0 && (
                <div className="flex items-center bg-emerald-500/20 border border-emerald-500/30 rounded-xl px-4 py-2">
                  <span className="text-emerald-400 text-sm font-semibold">
                    {comparisonPlayers.length}/2 oyuncu seçildi
                  </span>
                  {comparisonPlayers.length === 2 && (
                    <Button
                      size="sm"
                      onClick={() => setShowComparison(true)}
                      className="ml-3 bg-emerald-500 hover:bg-emerald-600 text-black font-bold cursor-pointer"
                    >
                      Karşılaştır
                    </Button>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Hero Stats */}
      <section className="bg-gradient-to-r from-slate-800/50 via-purple-800/30 to-slate-800/50 py-12">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div className="bg-gradient-to-br from-emerald-500/10 to-emerald-600/5 border border-emerald-500/20 rounded-2xl p-6 backdrop-blur-sm">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-emerald-400 text-sm font-semibold uppercase tracking-wide">Toplam Oyuncu</p>
                  <p className="text-4xl font-black text-white mt-2">{players.length}</p>
                </div>
                <div className="w-12 h-12 bg-emerald-500/20 rounded-xl flex items-center justify-center">
                  <Users className="w-6 h-6 text-emerald-400" />
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-br from-blue-500/10 to-blue-600/5 border border-blue-500/20 rounded-2xl p-6 backdrop-blur-sm">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-blue-400 text-sm font-semibold uppercase tracking-wide">En Yüksek Rating</p>
                  <p className="text-4xl font-black text-white mt-2">8.9</p>
                </div>
                <div className="w-12 h-12 bg-blue-500/20 rounded-xl flex items-center justify-center">
                  <Star className="w-6 h-6 text-blue-400" />
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-br from-purple-500/10 to-purple-600/5 border border-purple-500/20 rounded-2xl p-6 backdrop-blur-sm">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-purple-400 text-sm font-semibold uppercase tracking-wide">En Çok Gol</p>
                  <p className="text-4xl font-black text-white mt-2">38</p>
                </div>
                <div className="w-12 h-12 bg-purple-500/20 rounded-xl flex items-center justify-center">
                  <TrendingUp className="w-6 h-6 text-purple-400" />
                </div>
              </div>
            </div>

            <div className="bg-gradient-to-br from-orange-500/10 to-orange-600/5 border border-orange-500/20 rounded-2xl p-6 backdrop-blur-sm">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-orange-400 text-sm font-semibold uppercase tracking-wide">En Çok Asist</p>
                  <p className="text-4xl font-black text-white mt-2">25</p>
                </div>
                <div className="w-12 h-12 bg-orange-500/20 rounded-xl flex items-center justify-center">
                  <Users className="w-6 h-6 text-orange-400" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-6 py-12">
        {!selectedPlayerId && !showComparison && (
          <>
            {/* Players Grid */}
            <div
              className={
                viewMode === "grid"
                  ? "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8"
                  : "space-y-4"
              }
            >
              {players
                .filter((player) => player.name.toLowerCase().includes(search.toLowerCase()))
                .map((player) =>
                  viewMode === "grid" ? (
                    <Card
                      key={player.id}
                      className="group hover:scale-105 transition-all duration-500 bg-white/10 backdrop-blur-xl border-white/20 overflow-hidden hover:border-emerald-500/50 hover:shadow-2xl hover:shadow-emerald-500/10"
                    >
                      <div className="relative">
                        <div className="h-56 bg-gradient-to-br from-gray-800 to-gray-900 relative overflow-hidden">
                          <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />
                          <Avatar className="w-36 h-36 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 border-4 border-white/20 shadow-2xl">
                            <AvatarImage
                              src={player.image || "/placeholder.svg"}
                              alt={player.name}
                              className="object-cover"
                            />
                            <AvatarFallback className="text-2xl font-bold bg-gradient-to-r from-emerald-500 to-cyan-500 text-white">
                              {player.name
                                .split(" ")
                                .map((n) => n[0])
                                .join("")}
                            </AvatarFallback>
                          </Avatar>

                          <div className="absolute top-4 right-4">
                            <Badge
                              className={`${getPositionColor(player.position)} font-bold text-xs px-3 py-1 rounded-full shadow-lg`}
                            >
                              {player.position}
                            </Badge>
                          </div>

                          <div className="absolute bottom-4 left-4">
                            <div className="bg-black/60 backdrop-blur-md rounded-2xl px-4 py-2 border border-white/10">
                              <span className="text-3xl font-black text-emerald-400">{player.stats.rating}</span>
                            </div>
                          </div>
                        </div>
                      </div>

                      <CardContent className="p-6">
                        <div className="text-center mb-6">
                          <h3 className="text-xl font-black text-white mb-2">{player.name}</h3>
                          <div className="flex items-center justify-center space-x-3 text-sm text-gray-400">
                            <span className="font-semibold text-emerald-400">{player.team}</span>
                            <span>•</span>
                            <div className="flex items-center space-x-1">
                              <MapPin className="w-3 h-3" />
                              <span>{player.nationality}</span>
                            </div>
                          </div>
                        </div>

                        <div className="grid grid-cols-3 gap-4 mb-6">
                          <div className="text-center bg-gradient-to-br from-blue-500/10 to-blue-600/5 rounded-xl p-3 border border-blue-500/20">
                            <div className="text-2xl font-black text-blue-400">{player.stats.goals}</div>
                            <div className="text-xs text-gray-400 font-semibold uppercase tracking-wide">Gol</div>
                          </div>
                          <div className="text-center bg-gradient-to-br from-green-500/10 to-green-600/5 rounded-xl p-3 border border-green-500/20">
                            <div className="text-2xl font-black text-green-400">{player.stats.assists}</div>
                            <div className="text-xs text-gray-400 font-semibold uppercase tracking-wide">Asist</div>
                          </div>
                          <div className="text-center bg-gradient-to-br from-purple-500/10 to-purple-600/5 rounded-xl p-3 border border-purple-500/20">
                            <div className="text-2xl font-black text-purple-400">{player.stats.matches}</div>
                            <div className="text-xs text-gray-400 font-semibold uppercase tracking-wide">Maç</div>
                          </div>
                        </div>

                        <div className="flex space-x-3">
                          <Button
                            onClick={() => setSelectedPlayerId(player.id)}
                            className="flex-1 bg-gradient-to-r from-emerald-500 to-cyan-500 hover:from-emerald-600 hover:to-cyan-600 text-black font-bold rounded-xl h-12 shadow-lg hover:shadow-emerald-500/25 transition-all duration-300"
                          >
                            <Users className="w-4 h-4 mr-2" />
                            Detay
                          </Button>
                          <Button
                            variant="outline"
                            onClick={() => handleComparePlayer(player.id)}
                            className="flex-1 border-gray-600 text-black bg-white hover:bg-gray-100 hover:text-black rounded-xl h-12 font-bold cursor-pointer transition-all duration-300 hover:scale-105"
                          >
                            <TrendingUp className="w-4 h-4 mr-2" />
                            {comparisonPlayers.includes(player.id) ? "Seçildi" : "Karşılaştır"}
                          </Button>
                        </div>
                      </CardContent>
                    </Card>
                  ) : (
                    // List View
                    <Card
                      key={player.id}
                      className="bg-white/10 backdrop-blur-xl border-white/20 hover:border-emerald-500/50 transition-all duration-300"
                    >
                      <CardContent className="p-6">
                        <div className="flex items-center space-x-6">
                          <Avatar className="w-16 h-16 border-2 border-white/20">
                            <AvatarImage src={player.image || "/placeholder.svg"} alt={player.name} />
                            <AvatarFallback className="bg-gradient-to-r from-emerald-500 to-cyan-500 text-white font-bold">
                              {player.name
                                .split(" ")
                                .map((n) => n[0])
                                .join("")}
                            </AvatarFallback>
                          </Avatar>

                          <div className="flex-1">
                            <div className="flex items-center space-x-3 mb-2">
                              <h3 className="text-xl font-black text-white">{player.name}</h3>
                              <Badge className={`${getPositionColor(player.position)} text-xs px-2 py-1 rounded-full`}>
                                {player.position}
                              </Badge>
                            </div>
                            <p className="text-gray-400">
                              {player.team} • {player.nationality}
                            </p>
                          </div>

                          <div className="flex items-center space-x-8">
                            <div className="text-center">
                              <div className="text-2xl font-black text-blue-400">{player.stats.goals}</div>
                              <div className="text-xs text-gray-400 uppercase">Gol</div>
                            </div>
                            <div className="text-center">
                              <div className="text-2xl font-black text-green-400">{player.stats.assists}</div>
                              <div className="text-xs text-gray-400 uppercase">Asist</div>
                            </div>
                            <div className="text-center">
                              <div className="text-2xl font-black text-emerald-400">{player.stats.rating}</div>
                              <div className="text-xs text-gray-400 uppercase">Rating</div>
                            </div>
                          </div>

                          <div className="flex space-x-2">
                            <Button
                              onClick={() => setSelectedPlayerId(player.id)}
                              size="sm"
                              className="bg-gradient-to-r from-emerald-500 to-cyan-500 hover:from-emerald-600 hover:to-cyan-600 text-black font-bold"
                            >
                              Detay
                            </Button>
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => handleComparePlayer(player.id)}
                              className="border-gray-600 text-black bg-white hover:bg-gray-100 hover:text-black cursor-pointer transition-all duration-300 hover:scale-105"
                            >
                              {comparisonPlayers.includes(player.id) ? "Seçildi" : "Karşılaştır"}
                            </Button>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ),
                )}
            </div>
          </>
        )}
      </main>

      {/* Player Detail Modal */}
      {selectedPlayerId && (
        <PlayerDetail
          player={players.find((p) => p.id === selectedPlayerId)!}
          onBack={() => setSelectedPlayerId(null)}
        />
      )}

      {/* Player Comparison Modal */}
      {showComparison && comparisonPlayers.length === 2 && (
        <PlayerComparison
          players={comparisonPlayers.map((id) => players.find((p) => p.id === id)!)}
          onBack={() => {
            setShowComparison(false)
            setComparisonPlayers([])
          }}
        />
      )}
    </div>
  )
}
